# temper2
> ABC2

- toc: true 
- badges: true
- comments: true
- categories: [tutorial]


In [1]:
import numpy as np

In [ ]:
def gram_schmidt_columns(X):
    Q, R = np.linalg.qr(X)
    return Q

In [ ]:
def gs(X, row_vecs=True, norm = True):
    if not row_vecs:
        X = X.T
    Y = X[0:1,:].copy()
    for i in range(1, X.shape[0]):
        proj = np.diag((X[i,:].dot(Y.T)/np.linalg.norm(Y,axis=1)**2).flat).dot(Y)
        Y = np.vstack((Y, X[i,:] - proj.sum(0)))
    if norm:
        Y = np.diag(1/np.linalg.norm(Y,axis=1)).dot(Y)
    if row_vecs:
        return Y
    else:
        return Y.T

In [ ]:
import numpy

def gs_cofficient(v1, v2):
    return numpy.dot(v2, v1) / numpy.dot(v1, v1)

def multiply(cofficient, v):
    return map((lambda x : x * cofficient), v)

def proj(v1, v2):
    return multiply(gs_cofficient(v1, v2) , v1)

def gs(X):
    Y = []
    for i in range(len(X)):
        temp_vec = X[i]
        for inY in Y :
            proj_vec = proj(inY, X[i])
            #print "i =", i, ", projection vector =", proj_vec
            temp_vec = map(lambda x, y : x - y, temp_vec, proj_vec)
            #print "i =", i, ", temporary vector =", temp_vec
        Y.append(temp_vec)
    return Y

test = numpy.array([[3.0, 1.0], [2.0, 2.0]])
test2 = numpy.array([[1.0, 1.0, 0.0], [1.0, 3.0, 1.0], [2.0, -1.0, 1.0]])

print numpy.array(gs(test))
print numpy.array(gs(test2))

In [ ]:
CRAMERS RULE
if __name__ == "__main__":

    varA, varB, varC, varD, varE, varF = map(
        float, input("Enter a, b, c, d, e, f: ").split(","))

    if ((varA * varD) - (varB * varC)) == 0:
        print("The equation has no solution")
    else:
        solutionX = ((varE * varD) - (varB * varF)) / \
            ((varA * varD) - (varB * varC))

        solutionY = ((varA * varF) - (varE * varC)) / \
            ((varA * varD) - (varB * varC))

        print("x is " + str(solutionX) + " and y is " + str(solutionY))
@

# Eigen values and Eigen vectors

> Learning objectives  
- To define eigen values and vectors.  
- List a few properties which we will learn in detail in the future modules
- Using python, how to find eigen values and vectors.

Let A be a matrix and x be a vector. How to interpret Ax? If Ax is possible then Ax is a vector in a space spanned by the columns of A(column space of A). So another way to look at it is that A transforms vector x (i.e., change of scale, direction) into a vector y (=Ax) which lies in the column space of A.

Eigen vectors are a special type of vectors where they don't change direction but their length changes when multiplied with A OR Eigen vectors are those vectors that satisfies the equation $Ax=\lambda x$ where $\lambda$ can be a fraction, any integer etc. The number $\lambda$ is the eigen value.

**Note**- Let $A = I$ where $I$ is the identity matrix. For A, all vector x is an Eigen vector with eigen value = 1. 

**Example**

Lets illustrate the above definition using the example below

1. $Ax = \begin{pmatrix} .8 & .3 \\ .2 & .7 \end{pmatrix}x=\lambda x$

Here to extract the eigen values we must solve the following equation.

$(A-\lambda I)x=0 $ if the eigen value exist then the determinat of $A-\lambda I$ must be equal to zero. (why?)

Therefore the equation we must solve here (after all simplification) equals $2 \lambda ^2-3 \lambda +1 =0$ , we get $\lambda = 1,1/2$ and substituting for $\lambda$ in 1 we can extract the corresponding eigen vectors and they are    

$x=\begin{pmatrix}.6\\.4\end{pmatrix}, \lambda = 1$  
&    
$x=\begin{pmatrix}1\\-1\end{pmatrix}, \lambda = 1/2$

Let us think about the geometry of eigen vectors. when x is multiplied with A the eigen vector with $\lambda$ value = 1 stays the same in direction and in length but for $\lambda$ = 1/2 that eigen vectors magnitude halves. 



- **Elimination does not perserve the $\lambda$s**
- The product of n eigen values equals the determinant of the matrix
- The sum of n eigen values is equal to the sum of the diagonal values of a matrix which is called the trace of the matrix.
- One of the many applications of eigen values is that they help in computing large powers of a given matrix(what type of matrix?) i.e., Let's say $A^{100}$

## How to find eigen values and vectors in python?

In [54]:
A=np.array([[1,2,1],[3,5,2],[4,3,4]])
print(A)

[[1 2 1]
 [3 5 2]
 [4 3 4]]


In [55]:
eigen_values,eigen_vectors=np.linalg.eig(A)

In [56]:
print(eigen_values)

[ 8.37685015 -0.30893252  1.93208237]


In [57]:
print(eigen_vectors) # i th row represent the eigen vector of the respective 
                     # i th eigen value

[[-0.27355094 -0.78788511 -0.09183165]
 [-0.65834893  0.23001831 -0.47923262]
 [-0.70124644  0.57125181  0.87287058]]


In [58]:
Trace=A[0][0]+A[1][1]+A[2][2]
sum_of_eigen_values = round(np.sum(eigen_values),1)
print("trace of the matrix A = ",float(Trace))
print("Sum of the eigen values of A = ",sum_of_eigen_values)

trace of the matrix A =  10.0
Sum of the eigen values of A =  10.0


**To show that elimination does not perserve $\lambda$s.** 

Let P be a permutation matrix. P reduces row 2 by subtracting the values in row 2 with the corresponding values in row 1 multiplied by 3.






In [59]:
P=np.array([[1,0,0],[-3,1,0],[0,0,1]])

In [60]:
print(P@A) 

[[ 1  2  1]
 [ 0 -1 -1]
 [ 4  3  4]]


In [61]:
B=P@A

In [62]:
eig_values_B,eig_vectors=np.linalg.eig(B)

In [65]:
print("eigen values of A after elimination = ",eig_values_B)
print("eigen values of A bfore elimination = ",eigen_values)

eigen values of A after elimination =  [ 4.1925824  1.        -1.1925824]
eigen values of A bfore elimination =  [ 8.37685015 -0.30893252  1.93208237]


$(A-\lambda I)x=0 $ if the eigen value exist then the determinat of $A-\lambda I$ must be equal to zero. (why?)

Basically, if there exist a x other than the trivial zero/null vector it means that the null space spanned by $A-\lambda I$ contains vectors other than the null vector and also implies that the vectors sitting in the columns of $A-\lambda I$  are dependent which means the matrix don't have full column rank which implies that determinant of $A- \lambda I$ is equal to zero. 

> Summary  
- An eigenvector or characteristic vector of a linear transformation (read Matrix for now) is a nonzero vector that changes at most by a scalar factor when that linear transformation is applied to it.
- The sum and product of the A's equal the trace and delerminant of A respectively
- Elimination does not perserve the λs

**Note** The eigenvalues of $A^2$ & $A^{-1}$ are $\lambda ^2$ & $\lambda ^{-1}$ respectively