# Eigen values and Eigen vectors

> Topics covered-Basics,Diagonalizing a square matrix, Spectral theorem, Positive definite matrix, SVD. 

- toc: true 
- badges: true
- comments: true
- categories: [Linear Algebra Tutorial]

> Learning objectives  
- To define eigen values and vectors and state some of their properties 
- To factorize a square matrix $A$ into $S \Lambda S^{-1}$.
- Factorizing a symmetric matrix
- Spectral theorem
- Positive definite matrices
- Singular value decomposition


## Section 1: Basics

Let A be a matrix and x be a vector. How to interpret Ax? If Ax is possible then Ax is a vector in a space spanned by the columns of A(column space of A). So another way to look at it is that A transforms vector x (i.e., change of scale, direction) into a vector y (=Ax) which lies in the column space of A.

Eigen vectors are a special type of vectors where they don't change direction but their length changes when multiplied with A OR Eigen vectors are those vectors that satisfies the equation $Ax=\lambda x$ where $\lambda$ can be a fraction, any integer etc. The number $\lambda$ is the eigen value.

**Note**- Let $A = I$ where $I$ is the identity matrix. For A, all vector x is an Eigen vector with eigen value = 1. 

**Example**

Lets illustrate the above definition using the example below

1. $Ax = \begin{pmatrix} .8 & .3 \\ .2 & .7 \end{pmatrix}x=\lambda x$

Here to extract the eigen values we must solve the following equation.

$(A-\lambda I)x=0 $ if the eigen value exist then the determinat of $A-\lambda I$ must be equal to zero. (why?)

Therefore the equation we must solve here (after all simplification) equals $2 \lambda ^2-3 \lambda +1 =0$ , we get $\lambda = 1,1/2$ and substituting for $\lambda$ in 1 we can extract the corresponding eigen vectors and they are    

$x=\begin{pmatrix}.6\\.4\end{pmatrix}, \lambda = 1$  
&    
$x=\begin{pmatrix}1\\-1\end{pmatrix}, \lambda = 1/2$

Let us think about the geometry of eigen vectors. when x is multiplied with A the eigen vector with $\lambda$ value = 1 stays the same in direction and in length but for $\lambda$ = 1/2 that eigen vectors magnitude halves. 



- **Elimination does not perserve the $\lambda$s**
- The product of n eigen values equals the determinant of the matrix
- The sum of n eigen values is equal to the sum of the diagonal values of a matrix which is called the trace of the matrix.
- One of the many applications of eigen values is that they help in computing large powers of a given matrix(what type of matrix?) i.e., Let's say $A^{100}$

**Finding eigen values and vectors in python**

In [ ]:
import numpy as np

In [ ]:
A=np.array([[1,2,1],[3,5,2],[4,3,4]])
print(A)

[[1 2 1]
 [3 5 2]
 [4 3 4]]


In [ ]:
eigen_values,eigen_vectors=np.linalg.eig(A) #the obtained eigen vectors are unit vectors.

In [ ]:
print(eigen_values)

[ 8.37685015 -0.30893252  1.93208237]


In [ ]:
print(eigen_vectors) # i th row represent the eigen vector of the respective 
                     # i th eigen value

[[-0.27355094 -0.78788511 -0.09183165]
 [-0.65834893  0.23001831 -0.47923262]
 [-0.70124644  0.57125181  0.87287058]]


In [ ]:
Trace=A[0][0]+A[1][1]+A[2][2]
sum_of_eigen_values = round(np.sum(eigen_values),1)
print("trace of the matrix A = ",float(Trace))
print("Sum of the eigen values of A = ",sum_of_eigen_values)

trace of the matrix A =  10.0
Sum of the eigen values of A =  10.0


**To show that elimination does not perserve $\lambda$s.** 

Let P be a permutation matrix. P reduces row 2 by subtracting the values in row 2 with the corresponding values in row 1 multiplied by 3.






In [ ]:
P=np.array([[1,0,0],[-3,1,0],[0,0,1]])

In [ ]:
print(P@A) 

[[ 1  2  1]
 [ 0 -1 -1]
 [ 4  3  4]]


In [ ]:
B=P@A

In [ ]:
eig_values_B,eig_vectors=np.linalg.eig(B)

In [ ]:
print("eigen values of A after elimination = ",eig_values_B)
print("eigen values of A bfore elimination = ",eigen_values)

eigen values of A after elimination =  [ 4.1925824  1.        -1.1925824]
eigen values of A bfore elimination =  [ 8.37685015 -0.30893252  1.93208237]


$(A-\lambda I)x=0 $ if the eigen value exist then the determinat of $A-\lambda I$ must be equal to zero. (why?)

Basically, if there exist a x other than the trivial zero/null vector it means that the null space spanned by $A-\lambda I$ contains vectors other than the null vector and also implies that the vectors sitting in the columns of $A-\lambda I$  are dependent which means the matrix don't have full column rank which implies that determinant of $A- \lambda I$ is equal to zero. 

> Summary  
- An eigenvector or characteristic vector of a linear transformation (read Matrix for now) is a nonzero vector that changes at most by a scalar factor when that linear transformation is applied to it.
- The sum and product of the A's equal the trace and delerminant of A respectively
- Elimination does not perserve the λs

**Note** The eigenvalues of $A^2$ & $A^{-1}$ are $\lambda ^2$ & $\lambda ^{-1}$ respectively

**Note**  
if x is an eigen vector of A then Ax is simply reduced to $\lambda x$. Similarly, AAx=$\lambda \lambda x$.      
We can generalise it as $A^{n}x=\lambda ^{n}x$ where x is an eigen vector

## Section 2 : Diagonalizing a matrix using Eigen vectors

(2.1) Suppose the n by n matrix A has n **linearly independent eigen vectors** $x_1,x_2,...,x_n$ and S be a matrix whose columns contains these n independent eigen vectors then $S^{-1}AS = \Lambda$ where $\Lambda$ is eigen value matrix of A and also diagonalized matrix of A.

**What is the Eigen Value Matrix of A?**    
A matrix that contains eigen values of A in its diagonal position with off diagonal entry equals to zero.

Let's use (2.1) to rewrite A in a more meaningful way. From (2.1) $S^{-1}AS = \Lambda$ which implies that $AS=S\Lambda$ and this can be written as $A=S \Lambda S^{-1}$.

(2.2) $A=S \Lambda S^{-1}$ iff eigen vectors are linearly independent. OR in other words all the eigen vectors are unique. Matrices with repeated eigen values cannot be factorised into this form because S will not be invertible(why?)

**Note** S is not a unique matrix (why?)

**What is the meaning of (2.2)? How can we use it?**  
Let A be a matrix that can be factorised into (2.2) now it becomes easy to compute $A^{n}$ because $A^{n}=S \Lambda^{n} S^{-1}$

In [ ]:
def check_uniqueness(eigen_value):
  checker=[i for i in range(0,len(eigen_value)-1) for j in range(i+1,len(eigen_value)) if eigen_value[i]==eigen_value[j]]
  if len(checker)==0:
    return 'UNIQUE'
  else:
    return 'NOT UNIQUE'

In [ ]:
def diagonalizer(A):
  eigen_value,w=np.linalg.eig(A)
  if check_uniqueness(eigen_value)=='UNIQUE':
    return np.round(np.linalg.inv(w)@(A@w),3)
  else:
    print("Sorry the matrix does not have unique eigen values")

In [ ]:
A=np.array([[1,2,1],[3,5,2],[4,3,4]])
e,_=np.linalg.eig(A)
print(diagonalizer(A))
print()
print("the eigen values of the Matrix A = ", e)

[[ 8.377 -0.    -0.   ]
 [ 0.    -0.309  0.   ]
 [ 0.     0.     1.932]]

the eigen values of the Matrix A =  [ 8.37685015 -0.30893252  1.93208237]


### Setion 3:Diagonalizing a symmetric matrix

3.1 **Definition**   
A is a symmetric matrix if $A=A^{T}$

Let's explore using an example

$sys = \begin{pmatrix} 5 & 6 & 7\\ 6 & 3 & 2\\7 & 2 & 1 \end{pmatrix}$ we can see that sys is a 3*3 symmetric matrix.

In [ ]:
# intialising sys as a numpy array
sys = np.array([[5,6,7],[6,3,2],[7,2,1]])
# Let's check if the eigen values of sys matrix is unique or not
eig,_=np.linalg.eig(sys)
check_uniqueness(eig)=='UNIQUE'

True

Therefore eigen values of sys matrix is unique. 

Let's check out the eigen vector matrix of sys

In [ ]:
eig,S=np.linalg.eig(sys)
print("the eigen vector matrix of sys = \n", S)

the eigen vector matrix of sys = 
 [[ 0.72541697  0.66666667  0.17124772]
 [ 0.49566405 -0.33333333 -0.80200127]
 [ 0.47758494 -0.66666667  0.57224835]]


**What are the properties of S?**

In [ ]:
eig_vec1,eig_vec2,eig_vec3=S[:,0],S[:,1],S[:,2]

In [ ]:
# Let's  find out the dot product of the three eigen vectors among themselves
round(np.dot(eig_vec1,eig_vec2),3) 

-0.0

In [ ]:
round(np.dot(eig_vec2,eig_vec3),3)

0.0

In [ ]:
round(np.dot(eig_vec3,eig_vec1),3)

-0.0

The first thing therefore we notice is that the eigen vectors are orthogonal to each other

In [ ]:
np.round(S@S.T,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.round(S.T@S,3)

array([[ 1.,  0., -0.],
       [ 0.,  1.,  0.],
       [-0.,  0.,  1.]])

The second thing we notice is that the inverse of eigen vector matrix is its transpose therefore eigen vector matrix of a symmetric matrix is an orthogonal matrix

(3.2) **Definition** Orthogonal matrix  
An orthogonal matrix is a **real square matrix** whose columns and rows are orthogonal vectors OR $M*M^{-1}=I$ where M is the orthogonal matrix.

Here, the eigen vector matrix is not only orthogonal but also orthonormal because numpy normalises the obtained eigen vectors into unit vectors. 

For example:-

In [ ]:
round(np.dot(eig_vec1,eig_vec1),3)

1.0

**What are the properties of S?**  i.e., eigen vector matrix of a symmetric matrix
-  eigen vectors are orthogonal to each other
-  the inverse of eigen vector matrix is its transpose therefore eigen vector matrix of a symmetric matrix is an orthogonal matrix
- if the eigen vectors are unit vectors then the eigen vector matrix is an orthonormal matrix. 





Now let's answer the question, what is the form of matrix diagonalisation when the matrix is symmetric?

$S^{-1}AS=\Lambda$ this is when A is non symmetric    
when A is symmetric the equation becomes $S^{T}AS=\Lambda$

This journey culminates with the spectral theorem  

(3.3) **Spectral theorem**  
Every symmetric matrix A can be factorised as $S\Lambda S^{T}$ with $\Lambda$ matrix holding real eigen values in its diagonal position and orthonormal eigen vectors sitting in the columns of S matrix.

> Summary of Section 2 and 3
- We have learnt that A can be factorised into $A=S \Lambda S^{-1}$
- This factorisation can be used to seamlessly compute $A^{n}$ by using the following formula $A^{n}=S \Lambda^{n} S^{-1}$.

## Section 4: Positive definite & Singular Value Decomposition

(4.1) **Definition** Positive definite matrix   
A symmetric matrix whose eigen values are all positive

**How to test for positive definitness?**
The matrix A is positive definite if $x^{T}Ax>0$ for all nonzero vector X
